//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DBFirst
{
    using System;
    using System.Collections.Generic;
    
    public partial class Reservation
    {
        public int ReservationID { get; set; }
        public int SeatID { get; set; }
        public int MovieID { get; set; }
        public System.DateTime Date { get; set; }
        public string Email { get; set; }
    
        public virtual Movy Movy { get; set; }
        public virtual Movy Movy1 { get; set; }
        public virtual Seat Seat { get; set; }
        public virtual Seat Seat1 { get; set; }
        public virtual User User { get; set; }
    }
}
